defmodule PotokIdeWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :potok_ide

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_potok_ide_key",
    signing_salt: "c/bNj4LW",
    same_site: "Lax"
  ]

  @allowed_socket_origins [
    "https://potok.rs",
    "https://www.potok.rs",
    "https://potok-ide.fly.dev"
  ]

  @check_origin if Mix.env() == :prod, do: @allowed_socket_origins, else: false

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options], check_origin: @check_origin],
    longpoll: [connect_info: [session: @session_options], check_origin: @check_origin]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :potok_ide,
    gzip: not code_reloading?,
    only: PotokIdeWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :potok_ide
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug :enforce_canonical_host

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PotokIdeWeb.Router

  defp enforce_canonical_host(conn, _opts) do
    # LiveView socket transports cannot follow host redirects reliably.
    # Skip canonical enforcement for both websocket and longpoll endpoints.
    live_socket_path? =
      String.starts_with?(conn.request_path, "/live/websocket") or
        String.starts_with?(conn.request_path, "/live/longpoll")

    websocket_upgrade? =
      conn
      |> Plug.Conn.get_req_header("upgrade")
      |> Enum.any?(&String.downcase(&1) == "websocket")

    skip_canonical? = live_socket_path? or websocket_upgrade?

    # NOTE: Plug.SSL's `host:` option only fires for http scheme requests, so
    # we cannot rely on it here – Fly terminates TLS and forwards as HTTP with
    # X-Forwarded-Proto: https, meaning conn.scheme is already :https after
    # rewrite_on. We do the canonical-host 301 manually instead.
    case Application.get_env(:potok_ide, :canonical_host) do
      nil ->
        conn

      _canonical when skip_canonical? ->
        conn

      canonical when conn.host != canonical ->
        path = conn.request_path
        qs = conn.query_string
        location = if qs == "", do: "https://#{canonical}#{path}", else: "https://#{canonical}#{path}?#{qs}"

        conn
        |> Plug.Conn.put_resp_header("location", location)
        |> Plug.Conn.resp(301, "")
        |> Plug.Conn.halt()

      _canonical ->
        conn
    end
  end
end
